GET http://localhost:3000/api/admin/stores

Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsInJvbGUiOiJBRE1JTiIsImlhdCI6MTc0ODc5MzE5MCwiZXhwIjoxNzQ4ODc5NTkwfQ.w-rV3Sjog2uWtFr7HRZ_p4ii8XRMFjZFxACqZ7AO1aI
